# Generated by Django 2.2.1 on 2019-06-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.IntegerField()),
                ('batsman', models.CharField(max_length=100)),
                ('non_striker', models.CharField(max_length=100)),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('legbye_runs', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty_runs', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extra_runs', models.IntegerField()),
                ('total_runs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning_num', models.IntegerField()),
                ('batting_team', models.CharField(max_length=100)),
                ('bowling_team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Overs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.IntegerField()),
                ('bowler', models.CharField(max_length=100)),
                ('is_super_over', models.IntegerField()),
                ('inning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.Innings')),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('toss_winner', models.CharField(max_length=100)),
                ('toss_decision', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('player_of_match', models.CharField(blank=True, max_length=50, null=True)),
                ('venue', models.CharField(max_length=200)),
                ('umpire1', models.CharField(blank=True, max_length=100, null=True)),
                ('umpire2', models.CharField(blank=True, max_length=100, null=True)),
                ('umpire3', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.Season')),
            ],
        ),
        migrations.AddField(
            model_name='innings',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.Matches'),
        ),
        migrations.CreateModel(
            name='Delivery_Extra_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_dismissed', models.IntegerField()),
                ('dismissal_kind', models.IntegerField()),
                ('fielder', models.IntegerField()),
                ('delivery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.Deliveries')),
            ],
        ),
        migrations.AddField(
            model_name='deliveries',
            name='over_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl_app.Overs'),
        ),
    ]
