# Generated by Django 2.2.1 on 2019-06-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveries',
            name='over_id',
        ),
        migrations.AddField(
            model_name='deliveries',
            name='batting_team',
            field=models.CharField(default='ab', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='bowler',
            field=models.CharField(default='ab', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='bowling_team',
            field=models.CharField(default='ab', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='fielder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='inning',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='is_super_over',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='match_id',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='over',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveries',
            name='player_dismissed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Delivery_Extra_Data',
        ),
    ]
