# Generated by Django 2.2.1 on 2019-06-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl_app', '0002_auto_20190617_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='dismissal_kind',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
